name: liamhockley_me
description: Personal Blog Website for Liam Hockley
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  static_shock: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
